version: '3.1'
services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile-local
    mem_limit: 4g
    shm_size: 2g
    environment:
      DATABASE_USERNAME: 'postgres'
      DATABASE_PORT: '5432'
      DATABASE_HOST: 'db'
      DATABASE_PASSWORD: 'example'
      DECIDIM_APPLICATION_NAME: 'Decidim PESS'
      DECIDIM_MAILER_SENDER: 'comunicacio@bitlab.cat'
      DECIDIM_AVAILABLE_LOCALES: 'ca,en,es'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - gems:/usr/local/bundle:delegated
      - ~/.ssh/:/root/.ssh  #for deploy enter bash and run "eval $(ssh-agent -s)" and "ssh-add"
      - .:/decidim-plataformess
    ports:
      - "3000:3000"
      - "1234:1234"
    depends_on:
      - db

volumes:
  db: {}
  gems: {}
