#config/schedule.yml

metrics_job:
  cron: "30 1 * * *"
  class: "MetricsGenerationWorker"
  queue: metrics

data_job:
  cron: "3 3 * * *"
  class: "DataPortabilityWorker"
  queue: default

multimedia_gallery_job:
  cron: "0 1 * * *"
  class: "MultimediaGalleryWorker"
  queue: default
